from apps.common.choices import DocumentType, EvidenceType, RequirementCriticality


SEED_STANDARDS = [
    {
        "code": "ISO_9001",
        "name": "ISO 9001",
        "description": "Sistema de gestion de calidad orientado a control documental, operacion y mejora.",
        "version": "2015",
        "country": "Internacional",
        "requirements": [
            {
                "clause": "7.5",
                "title": "Control de informacion documentada",
                "requirement_text": "La organizacion debe definir como aprueba, actualiza, distribuye y protege la documentacion clave del sistema.",
                "process_area": "Control documental",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de control documental", "Listado maestro"],
                "expected_evidence": ["Registro de aprobacion", "Historial de cambios"],
                "verification_questions": [
                    "Existe un metodo definido para aprobar documentos antes de uso?",
                    "Se controla la version vigente y el acceso a documentos obsoletos?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.AUDIT_TRAIL,
            },
            {
                "clause": "8.4",
                "title": "Control de recepcion de insumos",
                "requirement_text": "La organizacion debe verificar lo recibido contra criterios definidos y dejar evidencia de aceptacion o rechazo.",
                "process_area": "Recepcion",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de recepcion", "Formato de inspeccion"],
                "expected_evidence": ["Registro diligenciado de recepcion"],
                "verification_questions": [
                    "Se definieron criterios de aceptacion y rechazo?",
                    "Queda trazabilidad de la revision realizada?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.RECORD,
            },
            {
                "clause": "8.5",
                "title": "Condiciones de almacenamiento",
                "requirement_text": "La organizacion debe mantener condiciones de almacenamiento que protejan integridad, identificacion y disponibilidad del producto.",
                "process_area": "Almacenamiento",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Procedimiento de almacenamiento", "Matriz de condiciones"],
                "expected_evidence": ["Registro de monitoreo", "Inspecciones"],
                "verification_questions": [
                    "Se definieron condiciones y responsables de control?",
                    "Existen evidencias de seguimiento periodico?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.RECORD,
            },
            {
                "clause": "8.7",
                "title": "Tratamiento de producto no conforme",
                "requirement_text": "La organizacion debe identificar, segregar y tratar salidas no conformes para evitar uso no intencional.",
                "process_area": "Producto no conforme",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de no conformes", "Formato de disposicion"],
                "expected_evidence": ["Registro de no conformidad", "Accion ejecutada"],
                "verification_questions": [
                    "Se define como identificar y contener el producto no conforme?",
                    "Se registra la decision y seguimiento?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.EXECUTED_CONTROL,
            },
            {
                "clause": "9.2",
                "title": "Auditoria interna planificada",
                "requirement_text": "La organizacion debe planificar auditorias internas, definir criterios y conservar resultados y acciones derivadas.",
                "process_area": "Auditoria interna",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Procedimiento de auditoria interna", "Programa anual"],
                "expected_evidence": ["Informe de auditoria", "Plan de accion"],
                "verification_questions": [
                    "Se definieron criterios, alcance y frecuencia?",
                    "Se conservan hallazgos y acciones?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.REPORT,
            },
            {
                "clause": "9.3",
                "title": "Revision por la direccion",
                "requirement_text": "La alta direccion debe revisar el desempeno del sistema y acordar decisiones sobre mejoras, recursos y acciones.",
                "process_area": "Revision por la direccion",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Procedimiento o agenda de revision", "Formato de acta"],
                "expected_evidence": ["Acta de revision", "Seguimiento a compromisos"],
                "verification_questions": [
                    "Se revisan entradas relevantes del sistema?",
                    "Quedan decisiones y responsables documentados?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.MINUTES,
                "required_evidence_type": EvidenceType.MINUTES,
            },
        ],
    },
    {
        "code": "ISO_13485",
        "name": "ISO 13485",
        "description": "Sistema de gestion de calidad para dispositivos medicos con enfasis en trazabilidad y control regulado.",
        "version": "2016",
        "country": "Internacional",
        "requirements": [
            {
                "clause": "4.2",
                "title": "Control formal de documentos y registros",
                "requirement_text": "La organizacion debe establecer control documentado sobre emision, cambios, disponibilidad y conservacion de registros del sistema.",
                "process_area": "Control documental",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de documentos y registros", "Listado maestro"],
                "expected_evidence": ["Versiones aprobadas", "Historial de cambios"],
                "verification_questions": [
                    "Los cambios tienen aprobacion antes de liberar la version?",
                    "Se conservan registros bajo reglas definidas?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.AUDIT_TRAIL,
            },
            {
                "clause": "7.4.3",
                "title": "Recepcion e inspeccion de producto comprado",
                "requirement_text": "La organizacion debe inspeccionar lo recibido, definir responsable de liberacion y asegurar trazabilidad del lote cuando aplique.",
                "process_area": "Recepcion",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de recepcion", "Formato de recepcion"],
                "expected_evidence": ["Registro de recepcion por lote", "Decision de liberacion"],
                "verification_questions": [
                    "Se establecen criterios de aceptacion, rechazo y cuarentena?",
                    "Se identifica quien libera el material?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.RECORD,
            },
            {
                "clause": "7.5.11",
                "title": "Preservacion en almacenamiento",
                "requirement_text": "La organizacion debe preservar el producto durante almacenamiento y controlar condiciones que afecten calidad o esterilidad.",
                "process_area": "Almacenamiento",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de almacenamiento", "Matriz de condiciones ambientales"],
                "expected_evidence": ["Registros ambientales", "Inspecciones de almacenamiento"],
                "verification_questions": [
                    "Se definieron condiciones criticas de preservacion?",
                    "Existen registros de monitoreo y reaccion ante desvio?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.MATRIX,
                "required_evidence_type": EvidenceType.RECORD,
            },
            {
                "clause": "8.3",
                "title": "Control de producto no conforme",
                "requirement_text": "La organizacion debe identificar el producto no conforme, evaluar su disposicion y dejar trazabilidad de la decision tomada.",
                "process_area": "Producto no conforme",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de producto no conforme", "Formato de disposicion"],
                "expected_evidence": ["Registro de no conforme", "Aprobacion de disposicion"],
                "verification_questions": [
                    "Se evita la liberacion no intencional del producto afectado?",
                    "La disposicion queda documentada y aprobada?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.EXECUTED_CONTROL,
            },
            {
                "clause": "8.2.4",
                "title": "Auditoria interna del sistema regulado",
                "requirement_text": "La organizacion debe auditar el sistema a intervalos planificados y documentar hallazgos, acciones y verificacion de cierre.",
                "process_area": "Auditoria interna",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Programa de auditoria", "Procedimiento de auditoria"],
                "expected_evidence": ["Informe de auditoria", "Verificacion de cierre"],
                "verification_questions": [
                    "Existe independencia del auditor cuando aplica?",
                    "Se verifican acciones derivadas?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.REPORT,
                "required_evidence_type": EvidenceType.REPORT,
            },
            {
                "clause": "5.6",
                "title": "Revision por la direccion con enfoque regulado",
                "requirement_text": "La direccion debe revisar resultados del sistema, quejas, acciones, recursos y oportunidades para mantener cumplimiento y eficacia.",
                "process_area": "Revision por la direccion",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Agenda o procedimiento de revision", "Formato de acta"],
                "expected_evidence": ["Acta firmada", "Seguimiento de compromisos"],
                "verification_questions": [
                    "Se revisan entradas relevantes para cumplimiento regulado?",
                    "Existen decisiones y responsables documentados?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.MINUTES,
                "required_evidence_type": EvidenceType.MINUTES,
            },
        ],
    },
    {
        "code": "BPADT_ARCSA",
        "name": "BPADT ARCSA",
        "description": "Buenas practicas y control documental sanitario con enfoque en trazabilidad, recepcion y control operativo.",
        "version": "MVP",
        "country": "Ecuador",
        "requirements": [
            {
                "clause": "CD-01",
                "title": "Control documental sanitario",
                "requirement_text": "La empresa debe mantener procedimientos vigentes, aprobados y disponibles para las operaciones reguladas y conservar sus cambios.",
                "process_area": "Control documental",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de control documental", "Listado maestro"],
                "expected_evidence": ["Aprobaciones", "Historial de cambios"],
                "verification_questions": [
                    "Los documentos sanitarios vigentes estan identificados y controlados?",
                    "Se evita el uso de versiones obsoletas?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.AUDIT_TRAIL,
            },
            {
                "clause": "RC-02",
                "title": "Recepcion con verificacion documentada",
                "requirement_text": "La recepcion debe validar condiciones, cantidades, integridad y trazabilidad de lo recibido antes de su liberacion.",
                "process_area": "Recepcion",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de recepcion", "Formato de recepcion"],
                "expected_evidence": ["Registro de recepcion", "Decision de aceptacion o rechazo"],
                "verification_questions": [
                    "Se documenta la condicion del producto al recibirlo?",
                    "Existe identificacion del lote o referencia aplicable?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.TEMPLATE,
                "required_evidence_type": EvidenceType.RECORD,
            },
            {
                "clause": "AL-03",
                "title": "Almacenamiento bajo condiciones definidas",
                "requirement_text": "La empresa debe almacenar materiales o producto en condiciones controladas, identificadas y monitoreadas.",
                "process_area": "Almacenamiento",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Procedimiento de almacenamiento", "Matriz de condiciones"],
                "expected_evidence": ["Registros de monitoreo", "Inspecciones internas"],
                "verification_questions": [
                    "Se definieron condiciones y criterios de segregacion?",
                    "Se evidencia seguimiento de temperatura, orden o limpieza cuando aplica?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.MATRIX,
                "required_evidence_type": EvidenceType.RECORD,
            },
            {
                "clause": "PNC-04",
                "title": "Manejo de producto no conforme o no apto",
                "requirement_text": "La empresa debe identificar, separar y decidir el destino de producto no conforme evitando su uso o despacho no autorizado.",
                "process_area": "Producto no conforme",
                "criticality": RequirementCriticality.HIGH,
                "expected_documents": ["Procedimiento de producto no conforme", "Formato de segregacion"],
                "expected_evidence": ["Registro de incidente", "Accion aplicada"],
                "verification_questions": [
                    "El producto no conforme queda identificado y segregado?",
                    "Se documenta la disposicion tomada?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.PROCEDURE,
                "required_evidence_type": EvidenceType.EXECUTED_CONTROL,
            },
            {
                "clause": "AI-05",
                "title": "Verificacion interna de cumplimiento",
                "requirement_text": "La empresa debe revisar periodicamente sus practicas documentadas y registrar hallazgos y acciones derivadas.",
                "process_area": "Auditoria interna",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Plan de verificacion interna", "Formato de informe"],
                "expected_evidence": ["Informe emitido", "Seguimiento de acciones"],
                "verification_questions": [
                    "La verificacion interna tiene alcance y criterios definidos?",
                    "Se registran hallazgos y acciones?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.REPORT,
                "required_evidence_type": EvidenceType.REPORT,
            },
            {
                "clause": "RD-06",
                "title": "Revision de desempeno y decisiones de direccion",
                "requirement_text": "La direccion debe revisar resultados operativos y regulatorios y dejar evidencia de decisiones y seguimiento.",
                "process_area": "Revision por la direccion",
                "criticality": RequirementCriticality.MEDIUM,
                "expected_documents": ["Formato de revision", "Agenda de seguimiento"],
                "expected_evidence": ["Acta de revision", "Compromisos con responsable"],
                "verification_questions": [
                    "Se analizan resultados y desvios regulatorios?",
                    "Se asignan responsables y fechas?",
                ],
                "requires_real_evidence": True,
                "required_document_type": DocumentType.MINUTES,
                "required_evidence_type": EvidenceType.MINUTES,
            },
        ],
    },
]
