# Generated by Django 5.2.13 on 2026-05-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNING', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='standards.standard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('PENDIENTE_DOCUMENTAL', 'Pendiente documental'), ('EN_REVISION', 'En revision'), ('CUMPLE_PARCIAL', 'Cumple parcial'), ('OBSERVADO', 'Observado'), ('VALIDADO_DOCUMENTALMENTE', 'Validado documentalmente'), ('IMPLEMENTADO', 'Implementado'), ('CERRADO', 'Cerrado')], default='NO_INICIADO', max_length=32)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('required_document_type', models.CharField(choices=[('POLITICA', 'Politica'), ('PROCEDIMIENTO', 'Procedimiento'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('MATRIZ', 'Matriz'), ('INFORME', 'Informe'), ('ACTA', 'Acta'), ('EVIDENCIA', 'Evidencia'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('required_evidence_type', models.CharField(choices=[('REGISTRO_DILIGENCIADO', 'Registro diligenciado'), ('ACTA', 'Acta'), ('INFORME', 'Informe'), ('CAPACITACION', 'Capacitacion'), ('CONTROL_EJECUTADO', 'Control ejecutado'), ('TRAZABILIDAD', 'Trazabilidad'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_not_applicable', models.BooleanField(default=False)),
                ('not_applicable_justification', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='standards.standardrequirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='implementation.project')),
            ],
            options={
                'ordering': ['requirement__sequence', 'requirement__clause', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'standard'), name='unique_project_name_per_company_standard'),
        ),
        migrations.AddConstraint(
            model_name='implementationchecklistitem',
            constraint=models.UniqueConstraint(fields=('project', 'requirement'), name='unique_checklist_item_per_project_requirement'),
        ),
    ]
