# Generated by Django 5.2.13 on 2026-05-28 19:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0002_implementationactivity'),
        ('implementation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('activity_type', models.CharField(choices=[('IMPLEMENTACION', 'Implementacion'), ('REVISION', 'Revision'), ('REUNION', 'Reunion'), ('SEGUIMIENTO', 'Seguimiento'), ('CAPACITACION', 'Capacitacion'), ('INFORME', 'Informe'), ('ADMINISTRATIVO', 'Administrativo'), ('OTRO', 'Otro')], default='IMPLEMENTACION', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('logged_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('approved_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='REGISTRADO', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('action_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='action_plans.actionplan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_worklogs', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worklogs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='implementation.project')),
            ],
            options={
                'ordering': ['-work_date', '-created_at', '-id'],
            },
        ),
    ]
