# Generated by Django 5.2.13 on 2026-05-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0002_worklogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='acceptance_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='ai_review_focus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='implementation_task',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='item_type',
            field=models.CharField(choices=[('DOCUMENTO', 'Documento'), ('EVIDENCIA', 'Evidencia'), ('ACTIVIDAD', 'Actividad'), ('CONTROL', 'Control'), ('DECISION', 'Decision')], default='CONTROL', max_length=24),
        ),
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='requires_document',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='requires_evidence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='implementationchecklistitem',
            name='review_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
