# Generated by Django 5.2.13 on 2026-05-29 20:44

import apps.implementation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0003_implementationchecklistitem_acceptance_criteria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(max_length=500, upload_to=apps.implementation.models.worklog_evidence_upload_to)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_worklog_evidences', to=settings.AUTH_USER_MODEL)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='implementation.worklogentry')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
