# Generated by Django 5.2.13 on 2026-05-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('other', 'Other')], default='ollama', max_length=32)),
                ('purpose', models.CharField(max_length=128)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('system_prompt', models.TextField()),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('other', 'Other')], default='ollama', max_length=32)),
                ('model_name', models.CharField(max_length=255)),
                ('operation_type', models.CharField(choices=[('review', 'Review'), ('embedding', 'Embedding'), ('chat', 'Chat')], default='review', max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='success', max_length=32)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_provider_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
