# Generated by Django 5.2.13 on 2026-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderlog',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('mock', 'Mock'), ('openai', 'OpenAI'), ('other', 'Other')], default='ollama', max_length=32),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('mock', 'Mock'), ('openai', 'OpenAI'), ('other', 'Other')], default='ollama', max_length=32),
        ),
    ]
