# Generated by Django 5.2.13 on 2026-05-26 13:59

import apps.action_plans.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documentchunk'),
        ('implementation', '0001_initial'),
        ('reviews', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=8)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('SUPERSEDIDO', 'Supercedido')], default='PENDIENTE', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='implementation.implementationchecklistitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_plans', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='reviews.finding')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_action_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='implementation.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='standards.standardrequirement')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('REGISTRO_DILIGENCIADO', 'Registro diligenciado'), ('ACTA', 'Acta'), ('INFORME', 'Informe'), ('CAPACITACION', 'Capacitacion'), ('CONTROL_EJECUTADO', 'Control ejecutado'), ('TRAZABILIDAD', 'Trazabilidad'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=apps.action_plans.models.evidence_upload_to)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('CARGADA', 'Cargada'), ('VALIDADA', 'Validada'), ('RECHAZADA', 'Rechazada'), ('ARCHIVADA', 'Archivada')], default='CARGADA', max_length=16)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('action_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='action_plans.actionplan')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='implementation.implementationchecklistitem')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_evidences', to='documents.document')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='reviews.finding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='implementation.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='standards.standardrequirement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
