# Generated by Django 5.2.13 on 2026-05-28 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0001_initial'),
        ('implementation', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('INICIO', 'Inicio'), ('AVANCE', 'Avance'), ('SEGUIMIENTO', 'Seguimiento'), ('REUNION', 'Reunion'), ('ENTREGABLE', 'Entregable'), ('BLOQUEO', 'Bloqueo'), ('CIERRE', 'Cierre')], default='SEGUIMIENTO', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('happened_on', models.DateField(default=django.utils.timezone.localdate)),
                ('next_follow_up_on', models.DateField(blank=True, null=True)),
                ('action_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='action_plans.actionplan')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementation_activities', to='implementation.implementationchecklistitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementation_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_activities', to='implementation.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementation_activities', to='standards.standardrequirement')),
            ],
            options={
                'ordering': ['-happened_on', '-created_at', '-id'],
            },
        ),
    ]
