# Generated by Django 5.2.13 on 2026-05-22 17:36

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implementation', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('POLITICA', 'Politica'), ('PROCEDIMIENTO', 'Procedimiento'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('MATRIZ', 'Matriz'), ('INFORME', 'Informe'), ('ACTA', 'Acta'), ('EVIDENCIA', 'Evidencia'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('file', models.FileField(max_length=500, upload_to=apps.documents.models.document_upload_to)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('CARGADO', 'Cargado'), ('PROCESANDO', 'Procesando'), ('LISTO', 'Listo'), ('FALLIDO', 'Fallido'), ('ARCHIVADO', 'Archivado')], default='CARGADO', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_metadata', models.JSONField(blank=True, default=dict)),
                ('processing_error', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='implementation.implementationchecklistitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='implementation.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='standards.standardrequirement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
