# Generated by Django 5.2.13 on 2026-05-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_start', models.PositiveIntegerField(default=0)),
                ('character_end', models.PositiveIntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_dimensions', models.PositiveIntegerField(default=0)),
                ('embedding_provider', models.CharField(choices=[('ollama', 'Ollama'), ('mock', 'Mock'), ('openai', 'OpenAI'), ('other', 'Other')], default='ollama', max_length=32)),
                ('embedding_model', models.CharField(blank=True, max_length=255)),
                ('embedding_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('LISTO', 'Listo'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=16)),
                ('embedding_error', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_index_per_document')],
            },
        ),
    ]
