# Generated by Django 5.2.13 on 2026-05-29 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_created_by'),
        ('documents', '0003_document_library_fields'),
        ('implementation', '0003_implementationchecklistitem_acceptance_criteria_and_more'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='library_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='companies.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='library_kind',
            field=models.CharField(choices=[('NORMA', 'Norma'), ('ANEXO', 'Anexo'), ('GUIA', 'Guia'), ('PLANTILLA', 'Plantilla'), ('EJEMPLO', 'Ejemplo'), ('CONTEXTO_EMPRESA', 'Contexto empresa'), ('OTRO', 'Otro')], default='OTRO', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='library_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='implementation.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='library_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='standards.standard'),
        ),
        migrations.AddField(
            model_name='document',
            name='library_usages',
            field=models.JSONField(blank=True, default=list, help_text='Usos permitidos: checklist, revision, RAG, plantilla o general.'),
        ),
        migrations.AddField(
            model_name='document',
            name='process_area',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
