# Generated by Django 5.2.13 on 2026-10-01 22:22

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_library_company_document_library_kind_and_more'),
        ('implementation', '0004_worklogevidence'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('POE', 'POE'), ('MATRIZ', 'Matriz'), ('FORMATO', 'Formato')], max_length=16)),
                ('process_area', models.CharField(blank=True, max_length=120)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_documents', to='implementation.implementationchecklistitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controlled_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_documents', to='implementation.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_documents', to='standards.standardrequirement')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=16)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='PLANTILLA', max_length=16)),
                ('content_hash', models.CharField(max_length=64)),
                ('change_summary', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('released_file', models.FileField(blank=True, max_length=500, upload_to=apps.documents.models.revision_release_upload_to)),
                ('released_hash', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('controlled_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.controlleddocument')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='control_revision', to='documents.document')),
            ],
            options={
                'ordering': ['-number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controlled_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_events', to='documents.controlleddocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_events', to='documents.documentrevision')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='controlleddocument',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_controlled_document_code_per_project'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('controlled_document', 'number'), name='unique_controlled_document_revision'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VIGENTE')), fields=('controlled_document',), name='unique_current_controlled_document_revision'),
        ),
    ]
