# Generated by Django 5.2.13 on 2026-05-26 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documentchunk'),
        ('implementation', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('REVISION_DOCUMENTAL', 'Revision documental'), ('CUMPLIMIENTO_NORMATIVO', 'Cumplimiento normativo'), ('CIERRE_NO_CONFORMIDAD', 'Cierre no conformidad'), ('PREPARACION_AUDITORIA', 'Preparacion auditoria'), ('IMPLEMENTACION', 'Implementacion')], default='REVISION_DOCUMENTAL', max_length=32)),
                ('overall_status', models.CharField(choices=[('CUMPLE', 'Cumple'), ('CUMPLE_PARCIAL', 'Cumple parcial'), ('NO_CUMPLE', 'No cumple'), ('NO_APLICA', 'No aplica'), ('NO_EVALUADO', 'No evaluado')], default='NO_EVALUADO', max_length=24)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=8)),
                ('summary', models.TextField(blank=True)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('system_prompt_used', models.TextField(blank=True)),
                ('user_prompt_used', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('retrieved_context', models.JSONField(blank=True, default=dict)),
                ('ai_model_used', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reviews', to='implementation.project')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_reviews', to='standards.standard')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_type', models.CharField(choices=[('BRECHA_DOCUMENTAL', 'Brecha documental'), ('BRECHA_IMPLEMENTACION', 'Brecha implementacion'), ('RIESGO_AUDITORIA', 'Riesgo auditoria'), ('NO_CONFORMIDAD_POTENCIAL', 'No conformidad potencial'), ('OBSERVACION', 'Observacion'), ('OPORTUNIDAD_MEJORA', 'Oportunidad de mejora')], default='BRECHA_DOCUMENTAL', max_length=32)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=8)),
                ('root_cause_suggestion', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En progreso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=16)),
                ('document_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.documentreview')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='implementation.project')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='standards.standardrequirement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CUMPLE', 'Cumple'), ('CUMPLE_PARCIAL', 'Cumple parcial'), ('NO_CUMPLE', 'No cumple'), ('NO_APLICA', 'No aplica'), ('NO_EVALUADO', 'No evaluado')], default='NO_EVALUADO', max_length=24)),
                ('evidence_found', models.TextField(blank=True)),
                ('gap', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=8)),
                ('recommendation', models.TextField(blank=True)),
                ('suggested_text', models.TextField(blank=True)),
                ('can_close_requirement', models.BooleanField(default=False)),
                ('requires_real_evidence', models.BooleanField(default=True)),
                ('missing_documents_or_evidence', models.JSONField(blank=True, default=list)),
                ('document_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_evaluations', to='reviews.documentreview')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_evaluations', to='standards.standardrequirement')),
            ],
            options={
                'ordering': ['requirement__sequence', 'requirement__clause', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document_review', 'requirement'), name='unique_requirement_evaluation_per_review_requirement')],
            },
        ),
    ]
