# Generated by Django 5.2.13 on 2026-05-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandardRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('requirement_text', models.TextField()),
                ('process_area', models.CharField(max_length=128)),
                ('criticality', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=16)),
                ('expected_documents', models.JSONField(blank=True, default=list)),
                ('expected_evidence', models.JSONField(blank=True, default=list)),
                ('verification_questions', models.JSONField(blank=True, default=list)),
                ('requires_real_evidence', models.BooleanField(default=True)),
                ('required_document_type', models.CharField(choices=[('POLITICA', 'Politica'), ('PROCEDIMIENTO', 'Procedimiento'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('MATRIZ', 'Matriz'), ('INFORME', 'Informe'), ('ACTA', 'Acta'), ('EVIDENCIA', 'Evidencia'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('required_evidence_type', models.CharField(choices=[('REGISTRO_DILIGENCIADO', 'Registro diligenciado'), ('ACTA', 'Acta'), ('INFORME', 'Informe'), ('CAPACITACION', 'Capacitacion'), ('CONTROL_EJECUTADO', 'Control ejecutado'), ('TRAZABILIDAD', 'Trazabilidad'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='standards.standard')),
            ],
            options={
                'ordering': ['standard__name', 'sequence', 'clause', 'id'],
                'constraints': [models.UniqueConstraint(fields=('standard', 'clause', 'title'), name='unique_requirement_per_standard_clause_title')],
            },
        ),
    ]
